<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="5nroor063" failures="1" tests="1" name="test" time="13.908" errors="0" timestamp="2024-06-19T19:35:02 MESZ">
  <testcase classname="tests.ContactFormTest" name="sendMessageTest" time="4.083">
    <failure type="java.lang.AssertionError" message="expected [Thank you for your message. It has been sent.x] but found [Thank you for your message. It has been sent.]">
      <![CDATA[java.lang.AssertionError: expected [Thank you for your message. It has been sent.x] but found [Thank you for your message. It has been sent.]
at tests.ContactFormTest.sendMessageTest(ContactFormTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- sendMessageTest -->
</testsuite> <!-- test -->
